### ISSUE TITLE
Default values chosen if none are curren

### ISSUE THREAD

**Issue by Kpop77** [Fredde87/tado#2]
Hello Fredrik!

I use your plugin for Tado Smart Thermostat. Really like the way how it works. Unfortunately, now I noticed that temperature has not been updated for a long time (2-3 months). I did not notice it before because it was not disturbing during summer :)
I've tried to reinstall the plugin but the result is even worst. It looks like Vera device can not login to tado.com and get devices list.

Log contains the following message:
_LuaInterface::CallFunction_Startup-1 device 134 function tado_init failed [string "-- Default values chosen if none are curren..."]:846: attempt to index local 'obj' (a nil value) <0x7699e520>
LuImplementation::StartLua running startup code for 134 I_Tado1.xml failed <0x7699e520>__

Could you give me advice what I'm doing wrong? 

Best Regards,
Kris

**Comment by Fredde87** [comment]
Hi Kris,

What version of the plugin are you running? Version 0.6 fixed a change in
Tado's API.

It is possible that they have changed their API again. I am currently away
but will be home next week so I can check then and release a new version if
it's something they have changed on their side.

As there is no official API I have had to reverse engineer their app. So
its very possible that something has been changed on their side and you are
the first person to report it to me.


Best Regards

Fredrik

**Comment by Kpop77** [comment]
Thank you Fredrik for quick answer. I'm using version 0.6 so it seems to be the proper one. 
I would be really grateful for your help.

Please let me know if you need from me any tests, additional information or whatever what I can do to help you with the case :)

Best Regards,
Kris

**Comment by Fredde87** [comment]
Hi Kris,

Sorry for the delay. I am now back home and had a look at this. The plugin
seems to work for me still. I had a look at line 846 where your error is
from.

It is a line in the code that looks up if your Vera unit is set to use
Celsius or Fahrenheit.

Can you open the following URL in your web browser,

http://<VERAIP>:3480/data_request?id=lu_sdata

This should return a lot of data about your Vera in json. The it should
start something like this though,

{ "full": 1, "version": "*1.7.3831*", "model": "Sercomm G450",
"zwave_heal": 1, "temperature": "C"

Do you have the "temperature": "C" (or F) value?

Also on the web interface, is the temperature format configured if you go
to Users & Account Info > Unit Settings > Temperature Format?

Are you using UI7?


Best Regards

Fredrik

**Comment by Kpop77** [comment]
Hi Fredrik!

Good to talk to you :) 
I'm using UI7. The web page _...:3480/data_request?id=lu_sdata_ returns following values:

full | 1
-- | --
version | "*1.7.4001*"
model | "Sercomm G450"
zwave_heal | 1
temperature | "C"
skin | "mios"
fwd1 | "vera-eu-oem-relay12.mios.com"
fwd2 | "vera-eu-oem-relay33.mios.com"
mode | 1

So temperature is set to Celsius. The same is set UI. After switch to 'F' issue is still the same. As you can see I'm using newer version of firmware so maybe there is some difference.  

There is one more information related to Tado, at the last line of the mentioned _data_request_ page:
_comment | "Tado.com Connection[137]: Startup Lua Failed_"

Would be good to say that I noticed a few other symptoms: 

- It is not possible to set-up password, user name and debug setting (0/1) from tab **Tado Settings** when I press **Set** button appears  "ERROR: Device not ready" message. The same setting can be edited and saved on the tab  **Advanced -> Variables**. 

- When I'm install your plug-in directly from Vera Apps page the error refers to line 846. When I overwrite all Tado files with github files, the error refers to line 815.  Seems to me that there are some difference between those two sources. 

If I can provide any additional information do not hesitate, just let me know.

Best Regards,
Kris

**Comment by Fredde87** [comment]
Hi Kris,

Thanks for checking. Can you SSH to your Vera and run the following
command. Does it return the same JSON data or does it fail?

curl -k -L -H "Content-Type: application/json" "
http://localhost:3480/data_request?id=lu_sdata"


Best Regards

Fredrik

**Comment by Kpop77** [comment]
Hi!

This command works and returns the same results when I use my Vera's local IP or 127.0.0.1. When **localhost** is in use appears error message **Couldn't resolve host 'localhost'**

Could it be related to issues described here:
https://support.getvera.com/customer/en/portal/articles/1710500-plugin-development#Issue:%20requests%20on%20port%203480%20/%2049451 
I means part: **Upcoming Security Enhancements**

Best Regards,
Kris

**Comment by Fredde87** [comment]
Hi Kris,

Interesting, not sure why your Vera can't resolve localhost to 127.0.0.1.

I dont think it is related to that article because it says,

"Ports 22, 80, 443, 3480, and 49451 will be blocked on all the network
interfaces, except the local loopback interface (localhost / 127.0.0.1)."

We are connecting to the local loopback interface so this should not apply
to us.

But to be on the safe side I can replace "localhost:3480" with "
127.0.0.1/port_3480/" as that works for me too.

If you install the latest version (0.6, sorry I had forgotten to upload the
latest code to github) and modify line 839 of L_Tado1.lua with the changes
we discussed. Then does that resolve the issue for you?

If this resolves the issue for you and it all works then I'll publish a new
version in the store for everyone.


Best Regards

Fredrik

**Comment by Kpop77** [comment]
Hi Fredrik!

This fix works! After change to _127.0.0.1/port_3480/_ my Vera is able to communicate to Tado. 
Thank you Fredrik for your great support!

Best Regards,
Kris
